[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET"
    Cache-Control = "public, max-age=31536000, immutable"

